"""
Signals API - Trading Signal History and Analysis

Agent: API Development Agent
Squad: Alpha
Sprint: Enhancement Phase

Provides REST API for querying trading signals generated by indicator agents.

Features:
- Get signal history with filters
- Get signals by indicator type
- Get signals by pair
- Get signal statistics
- Get signal accuracy metrics
- Real-time signal counts

Endpoints:
- GET /api/signals/history - Get signal history
- GET /api/signals/recent - Get most recent signals
- GET /api/signals/stats - Get signal statistics
- GET /api/signals/by_indicator/{indicator} - Get signals by indicator
- GET /api/signals/by_pair/{pair} - Get signals by pair
- GET /api/signals/accuracy - Get signal accuracy metrics

Agent: #20 API Development Agent
"""

from fastapi import APIRouter, Query, HTTPException, Depends
from typing import List, Optional, Dict, Any
from datetime import datetime, timedelta
from collections import defaultdict
import structlog

logger = structlog.get_logger(__name__)

router = APIRouter(prefix="/signals", tags=["signals"])

# In-memory signal storage (in production, use database)
# {signal_id: signal_data}
_signal_history: Dict[str, Dict[str, Any]] = {}

# Signal counts by type
_signal_counts: Dict[str, int] = defaultdict(int)


@router.get("/history")
async def get_signal_history(
    pair: Optional[str] = None,
    indicator: Optional[str] = Query(None, description="MA, RSI, MACD, BB, VOLUME"),
    signal_type: Optional[str] = None,
    start_date: Optional[str] = None,
    end_date: Optional[str] = None,
    limit: int = Query(100, le=500),
    offset: int = 0,
):
    """
    Get signal history with filtering.

    Args:
        pair: Filter by trading pair (e.g., 'BTC/USDC')
        indicator: Filter by indicator type
        signal_type: Filter by signal type (e.g., 'golden_cross', 'overbought')
        start_date: Start date (ISO format)
        end_date: End date (ISO format)
        limit: Maximum number of results
        offset: Offset for pagination

    Returns:
        Signal history with metadata
    """
    try:
        # Get all signals
        signals = list(_signal_history.values())

        # Apply filters
        if pair:
            signals = [s for s in signals if s.get("pair") == pair]

        if indicator:
            signals = [s for s in signals if s.get("indicator") == indicator.upper()]

        if signal_type:
            signals = [s for s in signals if s.get("signal_type") == signal_type]

        # Date filtering
        if start_date:
            start_dt = datetime.fromisoformat(start_date.replace("Z", "+00:00"))
            signals = [
                s for s in signals
                if datetime.fromisoformat(s.get("timestamp", "").replace("Z", "+00:00")) >= start_dt
            ]

        if end_date:
            end_dt = datetime.fromisoformat(end_date.replace("Z", "+00:00"))
            signals = [
                s for s in signals
                if datetime.fromisoformat(s.get("timestamp", "").replace("Z", "+00:00")) <= end_dt
            ]

        # Sort by timestamp (newest first)
        signals.sort(
            key=lambda x: datetime.fromisoformat(x.get("timestamp", "").replace("Z", "+00:00")),
            reverse=True
        )

        # Pagination
        total_count = len(signals)
        signals = signals[offset: offset + limit]

        return {
            "success": True,
            "signals": signals,
            "total_count": total_count,
            "limit": limit,
            "offset": offset,
            "filters": {
                "pair": pair,
                "indicator": indicator,
                "signal_type": signal_type,
                "start_date": start_date,
                "end_date": end_date,
            }
        }

    except Exception as e:
        logger.error("Failed to get signal history", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/recent")
async def get_recent_signals(
    limit: int = Query(20, le=100),
    min_strength: float = Query(0, ge=0, le=100),
):
    """
    Get most recent signals.

    Args:
        limit: Number of signals to return
        min_strength: Minimum signal strength (0-100)

    Returns:
        Recent signals sorted by timestamp
    """
    try:
        signals = list(_signal_history.values())

        # Filter by strength
        if min_strength > 0:
            signals = [s for s in signals if s.get("strength", 0) >= min_strength]

        # Sort by timestamp (newest first)
        signals.sort(
            key=lambda x: datetime.fromisoformat(x.get("timestamp", "").replace("Z", "+00:00")),
            reverse=True
        )

        return {
            "success": True,
            "signals": signals[:limit],
            "count": len(signals[:limit]),
        }

    except Exception as e:
        logger.error("Failed to get recent signals", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/stats")
async def get_signal_statistics(
    pair: Optional[str] = None,
    days: int = Query(7, ge=1, le=90),
):
    """
    Get signal statistics.

    Args:
        pair: Filter by trading pair
        days: Number of days to analyze

    Returns:
        Signal statistics and counts
    """
    try:
        # Calculate start date
        start_date = datetime.utcnow() - timedelta(days=days)

        signals = list(_signal_history.values())

        # Filter by pair
        if pair:
            signals = [s for s in signals if s.get("pair") == pair]

        # Filter by date
        signals = [
            s for s in signals
            if datetime.fromisoformat(s.get("timestamp", "").replace("Z", "+00:00")) >= start_date
        ]

        # Calculate statistics
        stats_by_indicator = defaultdict(lambda: {"count": 0, "avg_strength": 0, "signals": []})
        stats_by_type = defaultdict(int)
        stats_by_pair = defaultdict(int)

        total_strength = 0
        for signal in signals:
            indicator = signal.get("indicator", "UNKNOWN")
            signal_type = signal.get("signal_type", "unknown")
            signal_pair = signal.get("pair", "unknown")
            strength = signal.get("strength", 0)

            stats_by_indicator[indicator]["count"] += 1
            stats_by_indicator[indicator]["signals"].append(signal_type)
            total_strength += strength

            stats_by_type[signal_type] += 1
            stats_by_pair[signal_pair] += 1

        # Calculate average strength per indicator
        for indicator, data in stats_by_indicator.items():
            indicator_signals = [s for s in signals if s.get("indicator") == indicator]
            if indicator_signals:
                avg_strength = sum(s.get("strength", 0) for s in indicator_signals) / len(indicator_signals)
                stats_by_indicator[indicator]["avg_strength"] = round(avg_strength, 2)

        avg_strength = round(total_strength / len(signals), 2) if signals else 0

        return {
            "success": True,
            "period_days": days,
            "total_signals": len(signals),
            "avg_strength": avg_strength,
            "by_indicator": dict(stats_by_indicator),
            "by_type": dict(stats_by_type),
            "by_pair": dict(stats_by_pair),
            "start_date": start_date.isoformat(),
            "end_date": datetime.utcnow().isoformat(),
        }

    except Exception as e:
        logger.error("Failed to get signal statistics", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/by_indicator/{indicator}")
async def get_signals_by_indicator(
    indicator: str,
    limit: int = Query(50, le=200),
    min_strength: float = Query(0, ge=0, le=100),
):
    """
    Get signals by indicator type.

    Args:
        indicator: Indicator type (MA, RSI, MACD, BB, VOLUME)
        limit: Maximum number of signals
        min_strength: Minimum signal strength

    Returns:
        Signals from specified indicator
    """
    try:
        indicator = indicator.upper()

        signals = [
            s for s in _signal_history.values()
            if s.get("indicator") == indicator and s.get("strength", 0) >= min_strength
        ]

        # Sort by timestamp (newest first)
        signals.sort(
            key=lambda x: datetime.fromisoformat(x.get("timestamp", "").replace("Z", "+00:00")),
            reverse=True
        )

        return {
            "success": True,
            "indicator": indicator,
            "signals": signals[:limit],
            "count": len(signals[:limit]),
            "total_count": len(signals),
        }

    except Exception as e:
        logger.error("Failed to get signals by indicator", error=str(e), indicator=indicator)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/by_pair/{pair}")
async def get_signals_by_pair(
    pair: str,
    limit: int = Query(50, le=200),
    indicator: Optional[str] = None,
):
    """
    Get signals by trading pair.

    Args:
        pair: Trading pair (e.g., 'BTC/USDC')
        limit: Maximum number of signals
        indicator: Optional indicator filter

    Returns:
        Signals for specified pair
    """
    try:
        signals = [s for s in _signal_history.values() if s.get("pair") == pair]

        # Optional indicator filter
        if indicator:
            signals = [s for s in signals if s.get("indicator") == indicator.upper()]

        # Sort by timestamp (newest first)
        signals.sort(
            key=lambda x: datetime.fromisoformat(x.get("timestamp", "").replace("Z", "+00:00")),
            reverse=True
        )

        return {
            "success": True,
            "pair": pair,
            "signals": signals[:limit],
            "count": len(signals[:limit]),
            "total_count": len(signals),
        }

    except Exception as e:
        logger.error("Failed to get signals by pair", error=str(e), pair=pair)
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/accuracy")
async def get_signal_accuracy(
    indicator: Optional[str] = None,
    days: int = Query(30, ge=1, le=90),
):
    """
    Get signal accuracy metrics.

    NOTE: This requires trade outcome data to calculate accuracy.
    Placeholder implementation for now.

    Args:
        indicator: Filter by indicator type
        days: Number of days to analyze

    Returns:
        Signal accuracy metrics
    """
    try:
        # TODO: Implement actual accuracy calculation
        # This requires correlating signals with subsequent trade outcomes

        return {
            "success": True,
            "note": "Accuracy calculation requires trade outcome correlation",
            "indicator": indicator,
            "period_days": days,
            "accuracy_metrics": {
                "total_signals": len(_signal_history),
                "note": "Full implementation pending trade outcome correlation",
            }
        }

    except Exception as e:
        logger.error("Failed to get signal accuracy", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.post("/record")
async def record_signal(signal: Dict[str, Any]):
    """
    Record a new signal (called by indicator agents via event bus).

    Args:
        signal: Signal data

    Returns:
        Success confirmation
    """
    try:
        signal_id = f"{signal.get('pair', 'unknown')}-{signal.get('timestamp', datetime.utcnow().isoformat())}-{hash(str(signal))}"

        _signal_history[signal_id] = {
            "signal_id": signal_id,
            **signal
        }

        # Update counts
        indicator = signal.get("indicator", "UNKNOWN")
        _signal_counts[indicator] += 1

        logger.info(
            "Signal recorded",
            signal_id=signal_id,
            indicator=indicator,
            pair=signal.get("pair"),
            signal_type=signal.get("signal_type")
        )

        return {
            "success": True,
            "signal_id": signal_id,
        }

    except Exception as e:
        logger.error("Failed to record signal", error=str(e))
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/counts")
async def get_signal_counts():
    """
    Get signal counts by indicator.

    Returns:
        Signal counts
    """
    return {
        "success": True,
        "total_signals": len(_signal_history),
        "by_indicator": dict(_signal_counts),
    }


# Utility function to add signal (can be called by agents)
def add_signal(signal_data: Dict[str, Any]) -> str:
    """
    Add a signal to history.

    Args:
        signal_data: Signal data dictionary

    Returns:
        Signal ID
    """
    signal_id = f"{signal_data.get('pair', 'unknown')}-{signal_data.get('timestamp', datetime.utcnow().isoformat())}-{hash(str(signal_data))}"

    _signal_history[signal_id] = {
        "signal_id": signal_id,
        **signal_data
    }

    # Update counts
    indicator = signal_data.get("indicator", "UNKNOWN")
    _signal_counts[indicator] += 1

    return signal_id
